# Generated by Django 4.1.4 on 2023-02-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.IntegerField()),
                ('qualification', models.CharField(max_length=10)),
                ('offer_sal', models.FloatField()),
                ('location', models.TextField(max_length=30)),
            ],
        ),
    ]
